[MIG] l10n_de_location_nuts: Migration to 10.0
OCA/l10n-germany pull request #22
Opened 2017-06-13 18:33 UTC by chienandalu

Depends on:

[ ] https://github.com/OCA/partner-contact/pull/432
[ ] https://github.com/OCA/l10n-germany/pull/21

cc @Tecnativa

2017-06-18 23:27 UTC, pedrobaeza requested changes

2017-06-18 23:27 UTC, pedrobaeza commented on l10n_de_location_nuts/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/175/8.0
10.0

2017-06-18 23:27 UTC, pedrobaeza commented on l10n_de_location_nuts/README.rst
> +`here <https://github.com/OCA/l10n-germany/issues/new?body=module:%20l10n_de_location_nuts%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beh
Remove this according new README template

2017-06-18 23:27 UTC, pedrobaeza commented on l10n_de_location_nuts/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2017-06-18 23:27 UTC, pedrobaeza commented on l10n_de_location_nuts/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Put yourself here

2017-06-18 23:27 UTC, pedrobaeza commented on l10n_de_location_nuts/__manifest__.py
> +    'author': 'Antiun Ingeniería S.L., '
Remove Antiun

2017-06-20 16:17 UTC, pedrobaeza approved these changes

2017-09-13 19:24 UTC, pedrobaeza commented
Please rebase

2017-09-14 07:41 UTC, chienandalu commented
@pedrobaeza done

2017-09-21 00:06 UTC, pedrobaeza commented
OK, I think we can merge this one as well.

2017-09-21 00:06 UTC, merged