[10.0] [MIG] l10n_de_steuernummer
OCA/l10n-germany pull request #23
Opened 2017-06-22 08:43 UTC by pedrobaeza

Following #17, this is the migration to 10.0 of the module still in PR. The discussion ended that this can be useful and should be merged, but it has not done it yet. We can move forward to this version now, as the customer is moving to this version.

2017-06-22 08:45 UTC, pedrobaeza commented
cc @Tecnativa

2017-08-16 12:06 UTC, pedrobaeza commented
@chienandalu @cubells please review

2017-08-16 13:36 UTC, cubells requested changes
Minor changes. Typos.

2017-08-16 13:36 UTC, cubells commented on l10n_de_steuernummer/models/res_partner.py
> +            # This vat is not a Steue-IdNr., so if it is 10 or 11 digit
> This vat is not **an** Steue-IdNr.

2017-08-16 13:36 UTC, cubells commented on l10n_de_steuernummer/models/res_partner.py
> +            # length then we can assume that this is a old Steuernummer
> that this is **an** old Steuernummer

2017-08-16 13:36 UTC, cubells commented on l10n_de_steuernummer/README.rst
> +#. Put a SteuerNummer in the VAT field preceded by 'DE'.
> Put **an** SteuerNummer in the VAT

2017-08-16 13:48 UTC, chienandalu commented on l10n_de_steuernummer/models/res_partner.py
> +            # This vat is not a Steue-IdNr., so if it is 10 or 11 digit
@cubells I think that's not correct. Following grammar rules(https://rayli.net/blog/life/when-to-use-a-or-an/#First_why_the_confusion) a word like Steuer doen't begin with a vocal sound (although we spanish speaker tend to pronounce such words more like 'es...', than the proper 'ss'.

2017-08-16 14:00 UTC, chienandalu commented on l10n_de_steuernummer/models/res_partner.py
> +            # This vat is not a Steue-IdNr., so if it is 10 or 11 digit
Anyway s/Steue-IdNr/Steuer-IdNr

2017-08-16 14:03 UTC, cubells commented on l10n_de_steuernummer/models/res_partner.py
> +            # This vat is not a Steue-IdNr., so if it is 10 or 11 digit
@chienandalu 
I'm not an expert english speaker, sure.

So according to you, I made **"a stupid comment"** or **"an stupid comment"**?
:)

2017-08-16 14:14 UTC, chienandalu commented on l10n_de_steuernummer/models/res_partner.py
> +            # This vat is not a Steue-IdNr., so if it is 10 or 11 digit
@cubells Just an unfortunate observation :smile:

2017-08-16 14:39 UTC, chienandalu reviewed
@pedrobaeza Runbot doesn't build. Rebase maybe?

2017-08-16 14:51 UTC, pedrobaeza commented
The problem is an outdated .travis.yml. You can update it in a separate PR.

2017-08-16 16:19 UTC, chienandalu commented
@pedrobaeza Here you are https://github.com/OCA/l10n-germany/pull/24

2017-08-16 17:14 UTC, pedrobaeza commented
Please rebase and fix the comments that should be fixed (if any pending)

2017-08-17 08:01 UTC, pedrobaeza commented
@chienandalu @cubells give then your final blessing for merging.

2017-08-17 08:01 UTC, chienandalu commented
@pedrobaeza It still skips building runbot :confused:

2017-08-17 08:05 UTC, cubells approved these changes
:+1: 
LGTM

2017-08-17 08:07 UTC, pedrobaeza commented
But it's because you haven't rebased properly. Check the .travis.yml in the branch: https://github.com/Tecnativa/l10n-germany/blob/10.0-l10n_de_steuernummer/.travis.yml

2017-08-17 08:32 UTC, chienandalu approved these changes
@pedrobaeza Yes, I didn't update remotes.

Tested on runbot

2017-08-17 08:43 UTC, merged